"""empty message

Revision ID: 14edc50ad7cf
Revises: 
Create Date: 2017-03-07 08:46:24.304039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14edc50ad7cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weiboFavos')
    op.drop_table('commentFavos')
    op.drop_table('weiboCollects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weiboCollects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_time', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('weibo_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentFavos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_time', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('weibo_id', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weiboFavos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_time', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('weibo_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
