"""empty message

Revision ID: c074462e8a10
Revises: c5fd0f99cb72
Create Date: 2017-03-07 23:21:22.132035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c074462e8a10'
down_revision = 'c5fd0f99cb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibos', sa.Column('cite_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibos', 'cite_id')
    # ### end Alembic commands ###
