"""empty message

Revision ID: c5fd0f99cb72
Revises: 14edc50ad7cf
Create Date: 2017-03-07 17:49:34.680189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fd0f99cb72'
down_revision = '14edc50ad7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibos', sa.Column('cite_num', sa.Integer(), nullable=True))
    op.add_column('weibos', sa.Column('is_cite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibos', 'is_cite')
    op.drop_column('weibos', 'cite_num')
    # ### end Alembic commands ###
