"""empty message

Revision ID: f563e78338c3
Revises: c074462e8a10
Create Date: 2017-03-11 11:45:08.449371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f563e78338c3'
down_revision = 'c074462e8a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibos', sa.Column('has_cite', sa.Boolean(), nullable=True))
    op.drop_column('weibos', 'is_cite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibos', sa.Column('is_cite', sa.BOOLEAN(), nullable=True))
    op.drop_column('weibos', 'has_cite')
    # ### end Alembic commands ###
